plugins {
    id 'java'
}

group = 'com.zylquinal.argon2'
version = '2.1.4-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url 'https://projectlombok.org/edge-releases' }
}

dependencies {
    implementation 'org.jetbrains:annotations:23.0.0'
    compileOnly 'org.projectlombok:lombok:edge-SNAPSHOT'
    annotationProcessor 'org.projectlombok:lombok:edge-SNAPSHOT'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.3'
    testImplementation 'de.mkammerer:argon2-jvm:2.12'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.3'
}

test {
    useJUnitPlatform()
}