name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK 24'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 24

      - name: Setup phc-winner-argon2
        run: |
          chmod +x setup.sh
          bash setup.sh

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: |
            build/libs/*
            build/reports/*
